### PR TITLE
Added felixisweird to "Our Team" on AmogOS

### PR DESCRIPTION
**Pull request by felixbennett**
**top ten ways to be sus in 2021**

### CODE REVIEW

**Comment by F-fengzi** [comment]
3 confusing commits and inconsistent code
denied

**Comment by buddyjojo** [comment]
god that's like my first time using github but worse

**Comment by F-fengzi** [comment]
lmao

**Comment by buddyjojo** [comment]
image

**Comment by F-fengzi** [comment]
that's me on private repos

**Comment by buddyjojo** [comment]
lmao

**Comment by buddyjojo** [comment]
i use the git cli now
much easier tbh

**Comment by felixbennett** [comment]
Lol stop bullying me I started using GitHub last week lmfaoooo

**Comment by F-fengzi** [comment]
github desktop go brrr
but for systems without gui yeah

**Comment by F-fengzi** [comment]
oh github cli is a thing

**Comment by felixbennett** [comment]
I literally made added to about me in my IDE, made a fork, deleted about me in the fork, added new about me, it was called about me (1) when I added it so I renamed it lol

**Pull request closed without merging**
