### PR TITLE
halp , i make new good changes , 

### PR DESCRIPTION
**Pull request by moon1789**
me made changes only to start page , didnt touch anything also edit b4 merging anyways bai

### CODE REVIEW

**Comment by mobilegmYT** [comment]
> me made changes only to start page , didnt touch anything also edit b4 merging anyways bai

Can you go to settings for your fork and enable Github pages so we can preview changes

**Comment by F-fengzi** [comment]
this thing is so messed up lol
and lots of the changes are already done by me idk why it's here

**Comment by moon1789** [comment]
alright

> > me made changes only to start page , didnt touch anything also edit b4 merging anyways bai
> 
> Can you go to settings for your fork and enable Github pages so we can preview changes

**Comment by moon1789** [comment]
> this thing is so messed up lol
> and lots of the changes are already done by me idk why it's here

sed

**Comment by moon1789** [comment]
> this thing is so messed up lol
> and lots of the changes are already done by me idk why it's here

i didnt do any major stuff , just minor ;-;

**Pull request closed without merging**
